### ISSUE TITLE
Per Episode Metadata not being pulled

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#33]
I noticed with the 10.3.0 RC and a fresh install my episode metadata for anime was not being pulled. This seems to be a problem with the anime plugin as tv shows using the inbuilt metadata providers still work.

I'll look into it when I have free time.

**Comment by Matt07211** [comment]
```
[22:43:04] [INF] Creating virtual missing/unaired episode The Rising of the Shield Hero 1x25
[22:43:39] [ERR] Error in TheTVDB
System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at MediaBrowser.Controller.Entities.BaseItem.AddStudio(String name)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.MapSeriesToResult(MetadataResult`1 result, Series tvdbSeries, String metadataLanguage)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetMetadata(SeriesInfo itemId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
