### ISSUE TITLE
unhelpful AniDB error logging

### ISSUE THREAD

**Issue by hauntingEcho** [jellyfin/jellyfin-plugin-anime#48]
I'm seeing a bunch of entries like the following when indexing:
```
[16:30:01] [INF] Creating Season Season Unknown entry for Blue Exorcist
[16:30:12] [ERR] Error in AniDB
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_0.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Jellyfin.Plugin.Anime.Providers.AniDB.Identity.AniDbTitleDownloader.DownloadTitles_static(String titlesFile)
   at Jellyfin.Plugin.Anime.Providers.AniDB.Identity.AniDbTitleDownloader.Load_static(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Anime.Providers.Equals_check.Fast_xml_search(String a, String b, CancellationToken cancellationToken, Boolean return_AniDBid, Int32 x_)
   at Jellyfin.Plugin.Anime.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[16:30:12] [INF] Start AniSearch... Searching(Blue Exorcist)
```

I suspect that I got rate-limited.  However, as [the error message is in the body](https://wiki.anidb.net/HTTP_API_Definition#Errors), definitive information is missing.

**Comment by Cyan101** [comment]
More output for the error log would be nice, also seems when this happens my metadata just stops searching

**Comment by lenisko** [comment]
- Fresh IP address
- 3000ms delay 

Yet I'm getting those errors as well. 
Worth recompiling with more debug.
