### ISSUE TITLE
AniDB throwing 403 forbiddens when fetching metadata

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-plugin-anime#50]
When matching and fetching metadata from AniDB it throws 403's like candy 
the logs are as follows:
`[2020-02-11 00:35:20.329 +11:00] [ERR] Error in "AniDB"
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.<>c__DisplayClass164_1.<OpenReadAsync>b__0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---`

one 403 for each show being matched. any ideas?

**Comment by hauntingEcho** [comment]
this looks like the same log message I'm getting in #48

**Comment by zeldatp151** [comment]
I am also getting this.

**Comment by Cyan101** [comment]
This doesn't seem to be fixed even in v10

```
[23:54:22] [ERR] [36] MediaBrowser.Providers.TV.SeriesMetadataService: Error in AniSearch
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Jellyfin.Plugin.Anime.Providers.AniSearch.AniSearchSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[23:54:22] [INF] [36] Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoSeriesProvider: Start KitsuIo... Searching(Angel Beats!)
[23:54:28] [ERR] [36] MediaBrowser.Providers.Manager.ProviderManager: AniSearchSeriesImageProvider failed in GetImageInfos for type Series
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Jellyfin.Plugin.Anime.Providers.AniSearch.AniSearchSeriesImageProvider.GetImages(String aid, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```

**Comment by unmenschlich** [comment]
same problem here with anisearch
i use jellyfin 10.6.4, os Windows, x64 with anime v10.0.0.0

> [22:36:00] [ERR] [43] MediaBrowser.Providers.TV.SeriesMetadataService: Error in AniSearch
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Jellyfin.Plugin.Anime.Providers.AniSearch.AniSearchSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[22:36:00] [ERR] [43] MediaBrowser.Providers.Manager.ProviderManager: AniSearchSeriesImageProvider failed in GetImageInfos for type Series
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Jellyfin.Plugin.Anime.Providers.AniSearch.AniSearchSeriesImageProvider.GetImages(String aid, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
