### ISSUE TITLE
8.0.0 crahes jellifin

### ISSUE THREAD

**Issue by slch** [jellyfin/jellyfin-plugin-anime#63]
After (auto)update from 7.0.0 to 8.0.0 server stopped working.
After looking into logs and removing the Anime plugin jellifin returned back to normal (starting up, not that it works ideally in general)

<details> 
  <summary>Logs after installing (again after deleting)  8.0.0 plugin from plugin catalog</summary>
   [14:57:51] [WRN] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to ::1. Time (slow): 0:00:01.1460152. http://localhost:8096/Packages?PackageType=UserInstalled

[15:00:05] [INF] [33] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: Anime 8.0.0.0 Release

[15:00:05] [FTL] [19] Main: Unhandled Exception

System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'

   at System.Reflection.RuntimeAssembly.GetExportedTypes()

   at System.Reflection.Assembly.get_ExportedTypes()

   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__246_0(Assembly x)

   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()

   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'

   at System.Reflection.RuntimeAssembly.GetExportedTypes()

   at System.Reflection.Assembly.get_ExportedTypes()

   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__246_0(Assembly x)

   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()

   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)

   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

   at System.Threading.QueueUserWorkItemCallback.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()
</details>

Running a custom docker image from [here](https://github.com/jellyfin/jellyfin/issues/2615#issuecomment-602027461)
Also tried `jellyfin/jellyfin:latest` and `jellyfin/jellyfin:nightly`

**Comment by slch** [comment]
Tried installing other plugins - same thing.
Ok, removed all images, reinstalled `jellyfin/jellyfin:latest`.
Now it seems to work just fine.

Then it was smth with my system/image. Although i think i did not change anything there?

Anyway closing this issue.

**Comment by slch** [comment]
i think jellifin was still at `10.5.0` and plugins were requesting `10.5.2` - after cleaning up images and installing actually latest jellifin, all worked.

Not sure if it is supposed to be like that - requesting latest version `.dll` in any server.
Reopen just in case - please close if it's an issue with my setup.

**Comment by oddstr13** [comment]
Looks like the plugin was compiled against 10.5.2, yes.
I don't think this is going to be an issue going forward.
