### ISSUE TITLE
updating for 10.7.0

### ISSUE THREAD

**Issue by l3oncoder** [jellyfin/jellyfin-plugin-anime#94]
Hi there this plugin is currently broken for 10.7.0 

Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null.

Any idea how to fix thanks

**Comment by trin94** [comment]
I can confirm this. Installing the TVDB Provider does work, but the Anime plugin doesn't.

```
Error loading types from "Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null".
System.TypeLoadException: Method 'GetImageResponse' in type 'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider' from assembly 'Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
```

Log output:

```
[2020-12-06 20:25:37.571 +00:00] [WRN] [66] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Packages?PackageType=UserInstalled" to "127.0.0.1" in 0:00:01.0801521 with Status Code 200
[2020-12-06 20:25:49.583 +00:00] [INF] [66] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: "Anime" "10.0.0.0"
[2020-12-06 20:25:49.585 +00:00] [INF] [66] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[2020-12-06 20:25:49.586 +00:00] [WRN] [66] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://localhost:8096/Packages/Installed/Anime?AssemblyGuid=a4df60c5-6ab4-412a-8f79-2cab93fb2bc5&version=10.0.0.0" to "127.0.0.1" in 0:00:01.3494571 with Status Code 204
[2020-12-06 20:27:15.193 +00:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2020-12-06 20:27:15.194 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2020-12-06 20:27:15.195 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2020-12-06 20:27:15.195 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2020-12-06 20:27:15.196 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryMonitorStartup"
[2020-12-06 20:27:15.196 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "ExternalPortForwarding"
[2020-12-06 20:27:15.196 +00:00] [INF] [2] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[2020-12-06 20:27:15.199 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryChangedNotifier"
[2020-12-06 20:27:15.201 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "RecordingNotifier"
[2020-12-06 20:27:15.202 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UdpServerEntryPoint"
[2020-12-06 20:27:15.203 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UserDataChangeNotifier"
[2020-12-06 20:27:15.204 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DlnaEntryPoint"
[2020-12-06 20:27:15.205 +00:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
[2020-12-06 20:27:15.205 +00:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
[2020-12-06 20:27:15.207 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "NotificationEntryPoint"
[2020-12-06 20:27:15.210 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2020-12-06 20:27:15.210 +00:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DeviceAccessEntryPoint"
[2020-12-06 20:27:27.943 +00:00] [INF] [1] Main: Jellyfin version: "10.7.0"
[2020-12-06 20:27:27.960 +00:00] [INF] [1] Main: Environment Variables: ["[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]"]
[2020-12-06 20:27:27.962 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2020-12-06 20:27:27.963 +00:00] [INF] [1] Main: Operating system: "Linux"
[2020-12-06 20:27:27.963 +00:00] [INF] [1] Main: Architecture: X64
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: 64-Bit Process: True
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: User Interactive: True
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Processor count: 12
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Program data path: "/config"
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2020-12-06 20:27:28.141 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2020-12-06 20:27:28.184 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2020-12-06 20:27:28.184 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2020-12-06 20:27:28.184 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2020-12-06 20:27:28.189 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2020-12-06 20:27:28.189 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2020-12-06 20:27:28.197 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2020-12-06 20:27:28.260 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Anime_10.0.0.0/Jellyfin.Plugin.Anime.dll"
[2020-12-06 20:27:28.261 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error loading types from "Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null".
System.TypeLoadException: Method 'GetImageResponse' in type 'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider' from assembly 'Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
[2020-12-06 20:27:29.677 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: "OMDb" "10.7.0.0"
[2020-12-06 20:27:29.677 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: "MusicBrainz" "10.7.0.0"
[2020-12-06 20:27:29.677 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded plugin: "AudioDB" "10.7.0.0"
[2020-12-06 20:27:29.752 +00:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
```

Version: 10.7.0.0, docker image unstable `d02d1e899c3c`. Arch Linux

**Comment by oddstr13** [comment]
Yes, I can confirm. I'm holding off pushing out the update, due to how broken the plugin currently is. Especially the anilist provider is causing trouble iirc.

I'm contemplating splitting up the plugin into the individual providers instead of pushing an update of this one to the repo.

Which providers in particular do you use?


If you still want to try the plugin even knowing it's not working well, then you can find it in my testing repo at https://mirror3.openshell.no/jellyfin/plugins/unstable.json

On December 6, 2020 8:36:17 PM UTC, "Elias Müller" <notifications@github.com> wrote:
>I can confirm this. Installing the TVDB Provider does work, but the
>Anime plugin doesn't.
>
>```
>Error loading types from "Jellyfin.Plugin.Anime, Version=10.0.0.0,
>Culture=neutral, PublicKeyToken=null".
>System.TypeLoadException: Method 'GetImageResponse' in type
>'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider'
>from assembly 'Jellyfin.Plugin.Anime, Version=10.0.0.0,
>Culture=neutral, PublicKeyToken=null' does not have an implementation.
>   at System.Reflection.RuntimeAssembly.GetExportedTypes()
>at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1
>assemblies)+MoveNext()
>```
>
>Log output:
>
>```
>[2020-12-06 20:25:37.571 +00:00] [WRN] [66]
>Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response
>from "http://localhost:8096/Packages?PackageType=UserInstalled" to
>"127.0.0.1" in 0:00:01.0801521 with Status Code 200
>[2020-12-06 20:25:49.583 +00:00] [INF] [66]
>Emby.Server.Implementations.Updates.InstallationManager: New plugin
>installed: "Anime" "10.0.0.0"
>[2020-12-06 20:25:49.585 +00:00] [INF] [66]
>Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
>[2020-12-06 20:25:49.586 +00:00] [WRN] [66]
>Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response
>from
>"http://localhost:8096/Packages/Installed/Anime?AssemblyGuid=a4df60c5-6ab4-412a-8f79-2cab93fb2bc5&version=10.0.0.0"
>to "127.0.0.1" in 0:00:01.3494571 with Status Code 204
>[2020-12-06 20:27:15.193 +00:00] [INF] [2] Main: Received a SIGTERM
>signal, shutting down
>[2020-12-06 20:27:15.194 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
>[2020-12-06 20:27:15.195 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
>[2020-12-06 20:27:15.195 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
>[2020-12-06 20:27:15.196 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"LibraryMonitorStartup"
>[2020-12-06 20:27:15.196 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"ExternalPortForwarding"
>[2020-12-06 20:27:15.196 +00:00] [INF] [2]
>Emby.Server.Implementations.EntryPoints.ExternalPortForwarding:
>Stopping NAT discovery
>[2020-12-06 20:27:15.199 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"LibraryChangedNotifier"
>[2020-12-06 20:27:15.201 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"RecordingNotifier"
>[2020-12-06 20:27:15.202 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"UdpServerEntryPoint"
>[2020-12-06 20:27:15.203 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"UserDataChangeNotifier"
>[2020-12-06 20:27:15.204 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing "DlnaEntryPoint"
>[2020-12-06 20:27:15.205 +00:00] [INF] [2]
>Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
>[2020-12-06 20:27:15.205 +00:00] [INF] [2]
>Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
>[2020-12-06 20:27:15.207 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"NotificationEntryPoint"
>[2020-12-06 20:27:15.210 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
>[2020-12-06 20:27:15.210 +00:00] [INF] [2]
>Emby.Server.Implementations.ApplicationHost: Disposing
>"DeviceAccessEntryPoint"
>[2020-12-06 20:27:27.943 +00:00] [INF] [1] Main: Jellyfin version:
>"10.7.0"
>[2020-12-06 20:27:27.960 +00:00] [INF] [1] Main: Environment Variables:
>["[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_WEB_DIR,
>/jellyfin/jellyfin-web]", "[JELLYFIN_DATA_DIR, /config]",
>"[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_MEDIA_DIR,
>/media]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]",
>"[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]"]
>[2020-12-06 20:27:27.962 +00:00] [INF] [1] Main: Arguments:
>["/jellyfin/jellyfin.dll"]
>[2020-12-06 20:27:27.963 +00:00] [INF] [1] Main: Operating system:
>"Linux"
>[2020-12-06 20:27:27.963 +00:00] [INF] [1] Main: Architecture: X64
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: 64-Bit Process: True
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: User Interactive: True
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Processor count: 12
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Program data path:
>"/config"
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Web resources path:
>"/jellyfin/jellyfin-web"
>[2020-12-06 20:27:27.964 +00:00] [INF] [1] Main: Application directory:
>"/jellyfin/"
>[2020-12-06 20:27:28.141 +00:00] [INF] [1]
>Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting
>cache path: "/cache"
>[2020-12-06 20:27:28.184 +00:00] [INF] [1]
>Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses :
>"[127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
>[2020-12-06 20:27:28.184 +00:00] [INF] [1]
>Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions :
>"[]"
>[2020-12-06 20:27:28.184 +00:00] [INF] [1]
>Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses:
>"[127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
>[2020-12-06 20:27:28.189 +00:00] [INF] [1]
>Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
>[2020-12-06 20:27:28.189 +00:00] [INF] [1]
>Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
>[2020-12-06 20:27:28.197 +00:00] [INF] [1]
>Emby.Server.Implementations.ApplicationHost: Loading assemblies
>[2020-12-06 20:27:28.260 +00:00] [INF] [1]
>Emby.Server.Implementations.ApplicationHost: Loaded assembly
>"Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral,
>PublicKeyToken=null" from
>"/config/plugins/Anime_10.0.0.0/Jellyfin.Plugin.Anime.dll"
>[2020-12-06 20:27:28.261 +00:00] [ERR] [1]
>Emby.Server.Implementations.ApplicationHost: Error loading types from
>"Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral,
>PublicKeyToken=null".
>System.TypeLoadException: Method 'GetImageResponse' in type
>'Jellyfin.Plugin.Anime.Providers.KitsuIO.Metadata.KitsuIoEpisodeProvider'
>from assembly 'Jellyfin.Plugin.Anime, Version=10.0.0.0,
>Culture=neutral, PublicKeyToken=null' does not have an implementation.
>   at System.Reflection.RuntimeAssembly.GetExportedTypes()
>at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1
>assemblies)+MoveNext()
>[2020-12-06 20:27:29.677 +00:00] [INF] [1]
>Emby.Server.Implementations.ApplicationHost: Loaded plugin: "OMDb"
>"10.7.0.0"
>[2020-12-06 20:27:29.677 +00:00] [INF] [1]
>Emby.Server.Implementations.ApplicationHost: Loaded plugin:
>"MusicBrainz" "10.7.0.0"
>[2020-12-06 20:27:29.677 +00:00] [INF] [1]
>Emby.Server.Implementations.ApplicationHost: Loaded plugin: "AudioDB"
>"10.7.0.0"
>[2020-12-06 20:27:29.752 +00:00] [INF] [1] Main: Kestrel listening on
>"Any IP4 Address"
>```
>
>Version: 10.7.0.0, docker image unstable `d02d1e899c3c`. Arch Linux
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin-plugin-anime/issues/94#issuecomment-739559915

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by l3oncoder** [comment]
anidb or anilist, But I be more then happy to just use anidb

**Comment by Rassilion** [comment]
@oddstr13 

Tested version 11.2012.600.2703. It's working (fecthing metadata) but it's not respecting library settings. I selected anilist and anidb in settings but it's using KitsuIo and AniSearch. Is this normal, Do I need to clear plugins folder or something?

**Comment by l3oncoder** [comment]
https://drive.google.com/file/d/1g8niFVuD3p6uwf9flVPoWfy94z1N1wOY/view?usp=sharing use at own this kitsulo only  since anidb and anilist are kinda broken

**Comment by oddstr13** [comment]
Respecting library settings should be fixed with https://github.com/jellyfin/jellyfin/pull/4743

**Comment by oddstr13** [comment]
Providers has been split into separate plugins now. (see #82)

I have not tested functionality for any but the Kitsu one (which seems to be mostly working).

They are not published to the main repo yet, but they are available in my testing repo at https://mirror3.openshell.no/jellyfin/plugins/unstable.json
Probably best to remove the Anime plugin first.

Please report any problems to the respective git repos;
-    https://github.com/jellyfin/jellyfin-plugin-anilist
-    https://github.com/jellyfin/jellyfin-plugin-anidb
-    https://github.com/jellyfin/jellyfin-plugin-anisearch
-    https://github.com/jellyfin/jellyfin-plugin-kitsu

**Comment by rshxyz** [comment]
So should we be removing the plugin for 10.6.4? or just for the 10.7.0 rc2?

**Comment by crobibero** [comment]
Just for 10.7

**Comment by dephunk** [comment]
> 
> 
> Providers has been split into separate plugins now. (see #82)
> 
> I have not tested functionality for any but the Kitsu one (which seems to be mostly working).
> 
> They are not published to the main repo yet, but they are available in my testing repo at https://mirror3.openshell.no/jellyfin/plugins/unstable.json
> Probably best to remove the Anime plugin first.
> 
> Please report any problems to the respective git repos;
> 
>     * https://github.com/jellyfin/jellyfin-plugin-anilist
> 
>     * https://github.com/jellyfin/jellyfin-plugin-anidb
> 
>     * https://github.com/jellyfin/jellyfin-plugin-anisearch
> 
>     * https://github.com/jellyfin/jellyfin-plugin-kitsu

I'm confused... what do I download? I'm on 10.7

**Comment by NunzioArdi** [comment]
upgrade release for 10.7 ? (sorry about the ping)

**Comment by hugalafutro** [comment]
@dephunk 
Go to Dashboard, Plugins, then at top click Repositories, add new with address `https://mirror3.openshell.no/jellyfin/plugins/unstable.json`

then the new split metadata providers will appear in Plugins / Catalogue / Metadata

works in 10.7 (i'm only using anidb/anilist)

**Comment by oddstr13** [comment]
Looks like I forgot to get them pushed to the stable repo, but I have done so today.

:warning: Please remove my testing repo again, as that has a rather high probability of getting breaking changes.
If a plugin builds at all while I'm making changes, stuff goes to that repo!
